services:
  postgres:
    image: postgres:latest
    container_name: todo_pg
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: emma
      POSTGRES_PASSWORD: emma_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - todo_pg_data:/var/lib/postgresql/data

volumes:
  todo_pg_data: